# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#                           Конфигурация приложения
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Основной конфигурационный файл для базовых сервисов и функциональности приложения.
# Включает настройки для многопоточности, обработки почты и функций безопасности.

# ┌────────────────────────┐
# │   Основные настройки   │
# └────────────────────────┘
# Базовые параметры, определяющие основные операционные характеристики приложения

threads: 3                    # Управление параллельной обработкой
                             # Большие значения увеличивают производительность, но потребляют больше ресурсов

use_proxy_for_imap: false    # Включает защищенную маршрутизацию через прокси для IMAP соединений
                             # Рекомендуется для повышенной приватности и безопасности

keepalive_interval: 300      # Частота проверки соединения (секунды)
                             # Обеспечивает стабильное сетевое подключение

referral_codes:              # Реферальные коды
  - ""                       # Добавьте несколько записей для разных кампаний

# ┌────────────────────────┐
# │ Перенаправление почты  │
# └────────────────────────┘
# Настройки для автоматического перенаправления и обработки почты

redirect_settings:
  enabled: false             # Главный переключатель системы перенаправления почты
  email: ""                  # Целевой email для перенаправленных сообщений
  password: ""               # Учетные данные (используйте безопасное хранение!)
  imap_server: ""           # Адрес почтового сервера
  use_proxy: false           # Дополнительный уровень защиты через прокси

# ┌────────────────────────┐
# │   Сервисы CAPTCHA      │
# └────────────────────────┘
# Настройки интеграции для автоматического решения CAPTCHA

captcha_module: 2captcha     # Выбор сервиса CAPTCHA:
                             # ▸ 2captcha: Основное решение
                             # ▸ anticaptcha: Альтернативный вариант

two_captcha_api_key: ""      # Ключ аутентификации для 2captcha
anti_captcha_api_key: ""     # Ключ аутентификации для anticaptcha

# ┌────────────────────────┐
# │   Настройки запуска    │
# └────────────────────────┘
# Настройка задержки инициализации приложения

delay_before_start:
  min: 2                     # Минимальная продолжительность задержки (секунды)
  max: 3                     # Максимальная продолжительность задержки (секунды)
                             # Система случайно выберет значение в этом диапазоне

# ┌────────────────────────┐
# │  Справочник почтовых   │
# │       серверов         │
# └────────────────────────┘
# Полный список IMAP серверов для поддерживаемых почтовых провайдеров

imap_settings:
  # Глобальные сервисы
  gmail.com: imap.gmail.com          # Google Mail (требуется SSL)
  yahoo.com: imap.mail.yahoo.com     # Yahoo Mail (требуется SSL)
  icloud.com: imap.mail.me.com       # Apple iCloud (может потребоваться 2FA)

  # Российские сервисы
  mail.ru: imap.mail.ru              # Сервис Mail.ru

  # Европейские провайдеры
  gmx.com: imap.gmx.com              # GMX Международный
  gmx.net: imap.gmx.net              # GMX Германия - Основной
  gmx.de: imap.gmx.net               # GMX Германия - Дополнительный

  # Польские сервисы
  onet.pl: imap.poczta.onet.pl       # Onet Mail - Основной
  onet.com.pl: imap.poczta.onet.pl   # Onet Mail - Дополнительный
  op.pl: imap.poczta.onet.pl         # Onet Mail - Устаревший
  onet.eu: imap.poczta.onet.pl       # Onet Mail - Европейский
  gazeta.pl: imap.gazeta.pl          # Почтовый сервис Gazeta
